export const CATEGORY_ACTION_TYPES = {
    FETCH_CATGEORIES_START: 'category/FETCH_CATGEORIES_START',
    FETCH_CATGEORIES_FAILED: 'category/FETCH_CATGEORIES_FAILED',
    FETCH_CATGEORIES_SUCCESS: 'category/FETCH_CATGEORIES_SUCCESS'
}